/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multichatclientinterface;
import java.io.BufferedWriter;
import java.io.FileWriter;
import multichatclientcore.ActionType;
import java.util.Observable;
import java.util.Observer;
import multichatclientcore.ClientManager;
import multichatclientcore.Result;
import multichatclientcore.ResultCode;
import javax.swing.JOptionPane;
/**
 *
 * @author MinhLuong
 */
public class RoomChat extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form RoomChat
     */
    ClientManager mClientManager;
    String mMaPhong = "";
    String mTenPhong = "";
    ListRoom mListRoom;
    int mSoNguoi = 1;
    public RoomChat(ListRoom listRoom, ClientManager cm, String maPhong, String tenPhong, int soNguoi) {
        initComponents();
        mListRoom = listRoom;
        mClientManager = cm;
        mMaPhong = maPhong;
        mTenPhong = tenPhong;
        mSoNguoi = soNguoi;
        mClientManager.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoiDungChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessToSend = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtNoiDungChat.setEditable(false);
        txtNoiDungChat.setColumns(20);
        txtNoiDungChat.setRows(5);
        jScrollPane1.setViewportView(txtNoiDungChat);

        txtMessToSend.setColumns(20);
        txtMessToSend.setRows(5);
        jScrollPane2.setViewportView(txtMessToSend);

        btnSend.setText("Gửi");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setTitle("Nickname: " + mClientManager.mNickname + "      Tên phòng: " + mTenPhong + "     Mã Phòng: " + mMaPhong + "     Số người: " + mSoNguoi);
    }//GEN-LAST:event_formWindowOpened

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if(txtMessToSend.getText().trim().length()==0)
            return;
        mClientManager.SendMess(txtMessToSend.getText().trim());
        try {
            FileWriter fw = new FileWriter("D:\\NetBeans-17\\input.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(txtMessToSend.getText());
            bw.newLine();
            bw.close();
            fw.close();
        } catch (Exception e) {
        }
        txtMessToSend.setText("");
    }//GEN-LAST:event_btnSendActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        mClientManager.LeaveRoom();
        mClientManager.deleteObserver(this);
        mClientManager.addObserver(mListRoom);
        mListRoom.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    @Override
    public void update(Observable o, Object arg) 
    {
        Result result = (Result)arg;
        
        if(result.mResultCode.equals(ResultCode.ERROR))
        {
            JOptionPane.showMessageDialog(null, result.mContent, "Thất bại", JOptionPane.ERROR_MESSAGE);
            return;
        }
        switch (result.mActionType)
        {
            case ActionType.SEND_MESSAGE:
            {
                String[] lines = result.mContent.split(";", -1);
                String sender = lines[0];
                String messContent = lines[1];
                messContent = messContent.replaceAll("<br>", "\n");  //khi tin nhắn gửi đi đã thay ký tự xuống dòng bằng <br> nên khi nhận về thì thay ngược lại
                if(sender.equals(mClientManager.mNickname))
                    txtNoiDungChat.append("You: " + messContent + "\n");
                else
                    txtNoiDungChat.append(sender + ": " + messContent + "\n");
                break;
            }
            case ActionType.UPDATE_NUMBER_USER:
            {
                String soNguoi = result.mContent;
                mSoNguoi = Integer.parseInt(soNguoi);
                this.setTitle("Nickname: " + mClientManager.mNickname + "      Tên phòng: " + mTenPhong + "     Mã Phòng: " + mMaPhong + "     Số người: " + mSoNguoi);
                break;
            }
            case ActionType.NOTIFY_JUST_JOIN_ROOM:
            {
                String userJoin = result.mContent;
                txtNoiDungChat.append("<" + userJoin + "> vừa tham gia phòng\n" );
                break;
            }
            case ActionType.NOTIFY_JUST_LEAVE_ROOM:
            {
                String userJoin = result.mContent;
                txtNoiDungChat.append("<" + userJoin + "> vừa rời phòng\n" );
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMessToSend;
    private javax.swing.JTextArea txtNoiDungChat;
    // End of variables declaration//GEN-END:variables
}
